// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO6VcJVUAu_eZwOLTQS_ne_5CPhLNlNPg',
    appId: '1:530468062811:web:3269b805f3d93386f8217e',
    messagingSenderId: '530468062811',
    projectId: 'mynotes-af2ad',
    authDomain: 'mynotes-af2ad.firebaseapp.com',
    storageBucket: 'mynotes-af2ad.appspot.com',
    measurementId: 'G-47V41Z6XMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoy2PnVgjWdwgxFsXuSzeqsU__7oKOqkk',
    appId: '1:530468062811:android:7c9b6df990aacc83f8217e',
    messagingSenderId: '530468062811',
    projectId: 'mynotes-af2ad',
    storageBucket: 'mynotes-af2ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPLoBiX3YT6Le1DNbPKsnE6qNCipOCSCM',
    appId: '1:530468062811:ios:46e6b1e2e087b206f8217e',
    messagingSenderId: '530468062811',
    projectId: 'mynotes-af2ad',
    storageBucket: 'mynotes-af2ad.appspot.com',
    iosClientId: '530468062811-rlhcrpp6qenthh1t5qmqi6dkfemjgg26.apps.googleusercontent.com',
    iosBundleId: 'com.leilaabdel.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPLoBiX3YT6Le1DNbPKsnE6qNCipOCSCM',
    appId: '1:530468062811:ios:46e6b1e2e087b206f8217e',
    messagingSenderId: '530468062811',
    projectId: 'mynotes-af2ad',
    storageBucket: 'mynotes-af2ad.appspot.com',
    iosClientId: '530468062811-rlhcrpp6qenthh1t5qmqi6dkfemjgg26.apps.googleusercontent.com',
    iosBundleId: 'com.leilaabdel.mynotes',
  );
}
